apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-ingress
  namespace: front
spec:
  podSelector:
    matchLabels:
      app: react
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8080